<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio sourcing module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Sourcing\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * What each lodge traded with charges: a currency, a board, and its periods.
 */
final class Version20261007000300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'sourcing_lodge_contract';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE sourcing_lodge_contract (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, partner_id VARCHAR(36) NOT NULL, currency VARCHAR(3) NOT NULL, board VARCHAR(40) NOT NULL, periods JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C53B5609393F8FE ON sourcing_lodge_contract (partner_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE sourcing_lodge_contract');
    }
}
