<?php

declare(strict_types=1);

/*
 * This file is part of the vivutio sourcing module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vivutio\Sourcing\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Rooms requested from accommodation partners.
 */
final class Version20261006000700 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'sourcing_room_request';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE sourcing_room_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, reference VARCHAR(16) NOT NULL, partner_id VARCHAR(36) NOT NULL, party VARCHAR(120) NOT NULL, arrival DATE NOT NULL, nights INT NOT NULL, lines JSON NOT NULL, notes TEXT NOT NULL, our_reference VARCHAR(120) NOT NULL, their_reference VARCHAR(60) NOT NULL, status VARCHAR(16) NOT NULL, history JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CB368E2ED17F50A6 ON sourcing_room_request (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CB368E2EAEA34913 ON sourcing_room_request (reference)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE sourcing_room_request');
    }
}
